version: 2

# Build documentation in the following formats
formats:
  - htmlzip

# Build documentation with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Specify the Python environment to use
build:
  os: ubuntu-24.04
  tools:
    python: "3.12" # Stable target for hosting environments

python:
  install:
    # This automatically runs an editable install of your package
    # so autodoc can find your code without path tricks!
    - method: pip
      path: .
