[project]
name = "ocd-gd"
version = "0.1.0"
description = "This is the main public repo for Orbital Chaos Detector package"
readme = "README.md"
requires-python = ">=3.13"
license = { file = "LICENSE" }
authors = [
    { name = "Asad Arshad", email = "asad.mail@icloud.com" }
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Scientific/Engineering :: Physics",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]

dependencies = [
    "agama>=1.0.0",
    "astropy>=8.0.0",
    "matplotlib>=3.11.0",
    "numba>=0.65.1",
    "numpy>=2.5.0",
    "plotly>=6.8.0",
    "scipy>=1.18.0",
    "tqdm>=4.67.3",
]

[tool.uv.sources]
agama = { git = "https://github.com/GalacticDynamics-Oxford/AGAMA.git", branch = "master" }

[project.optional-dependencies]
dev = [
    "myst-parser>=4.0.0",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "sphinx>=9.1.0",
    "sphinx-rtd-theme>=3.0.0",
]
cli = [
    "rich>=15.0.0",
]

[build-system]
requires = ["uv_build>=0.5.0,<0.14"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.1",
]

[tool.uv.extra-build-dependencies]
agama = ["numpy", "setuptools", "wheel", "scipy", "matplotlib"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = [
    "-v",
    "--strict-markers",
    "-W ignore::DeprecationWarning",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://github.com/def-fun7/ocd-gd"
Repository = "https://github.com/def-fun7/ocd-gd.git"
Docs = "https://ocd-gd.readthedocs.io/en/latest/"
Issues = "https://github.com/def-fun7/ocd-gd/issues"

[project.scripts]
setup-env = "scripts.setup_env:main"
